### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by shashisaurav** [aacotroneo/laravel-saml2#1]
It says "SAML Response not found, Only supported HTTP_POST Binding" trying to log in.

**Comment by aacotroneo** [comment]
mmm... this is one is hard to tell. It may be a configuration error on the Idp. When you require login, you are redirected to the Idp to authenticate, and then redirected back again to your app with an HTTP post that contains the assertion.

May be you can play a little bit in the Saml2Controller.php and see what is coming in the request. Remember that by a onelogin limitation, only HTTP_POST binding is supported (i.e. assertion should be in the post body)

**Comment by aacotroneo** [comment]
close inactive
