### ISSUE TITLE
not returning to my application once logged in

### ISSUE THREAD

**Issue by vdellangela** [aacotroneo/laravel-saml2#100]
I'm trying to connect to a F5 IDP and I'm facing an issue when the user has logged in, it doesn't return back to the application. Instead it goes to the F5 dashboard that lists all the application of the company...

I talked with the person managing the IDP and he told me I needed to set the SP to initiated but I can't find it anywhere in the documentation.

Are you aware of any settings that I would indicate the return url?
I tried to update "loginRoute" but it didn't seem to have any effect.

Thanks

**Comment by aacotroneo** [comment]
hmmm... i don't know the idp, you'd have to ask them about it. this sp
allows for both flows. you need to configure that at the idp. also initiate
the login from your app rather than their side.


El 16 jul. 2017 9:20 p.m., "Valentin" <notifications@github.com> escribió:

I'm trying to connect to a F5 IDP and I'm facing an issue when the user has
logged in, it doesn't return back to the application. Instead it goes to
the F5 dashboard that lists all the application of the company...

I talked with the person managing the IDP and he told me I needed to set
the SP to initiated but I can't find it anywhere in the documentation.

Are you aware of any settings that I would indicate the return url?
I tried to update "loginRoute" but it didn't seem to have any effect.

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/aacotroneo/laravel-saml2/issues/100>, or mute the thread

**Comment by vdellangela** [comment]
Thanks for your feedback.
I don't know this IDP either haha - it was working fine with ADFS.

Anyway, from the IDP manager, it seems that I need to turn on a setting (SP initiated) on my side but I can't find anything.

**Comment by vdellangela** [comment]
Also I noticed that when the user access my app and get redirected to the SSO login page.
The URL doesn't contain any token or redirect url.

On my another project working with ADFS and simpleSaml, I can see both parameters on the SSO login page. However I'm not too sure if it's because it's another IDP or if the settings are not correct?

I have updated on the config file:
$idp_host = url of my idp
$x509 and private key = my ssl certificate

**Comment by vdellangela** [comment]
Thanks for your feedback.

First I'd like to confirm that the login is initiated on my app. So the user gets redirected to the IDP login page afterwards but never gets back to my app once logged in.

Also I checked the requests being sent to the IDP and I could see a token and a relaystate url but I was suprise not to see any redirect_url parameter.

I suppose that is why the IDP is not redirecting to my app.

This is the current request: 
https://myidpurl,com/saml2/idp/SSOService.php?SAMLRequest=lVNNj9owEL3vr0C5k%2FCxgWJBJAr9QGUBkbSHXirjTDZWE9v1TBb239dJ2IWuVkj1JdL4zXvPbyZT5GVh2LyiXO3hTwVIdx13TmWhkDWXM6%2ByimmOEpniJSAjweL5w5oN%2FB4zVpMWuvDetN3u4ohgSWrVtq2WM2%2B7%2BbTeflltfo1E%2BGEIowmfwCg8ZOH9SIgwFJPJuJcNR4PhYHjg4ZCLtvUHWHQ8M8%2FRtpWd1U8yBbtxqjPvm1SphfSsg1jBSiFxRa6j1x93e%2BNuf5z0%2Buw%2BZP3Jzxa3dDFIxakhzokMsiCQqekW%2BlEqHwh8wSnnz4YLmUnhC10Gca4Bg%2FrtgxobxPE2BvskBfgmN6%2FemrQ%2BOldSPd4O6dCCkH1Nkl13t42TlmT%2BEt5CK6xKsGeZ7%2Fv1xW1mtaJCKkDU%2FlFS%2FrsNorHamuQCvahhnNYF1qRjo%2F9gKIF4yolPg2uCC6Vh9RBWy50upHhu6vX5rG3J6fbj64pMu1kDZaaeMhIo8l5Z5kWhjwsLnNyYyVbgdYJ%2FtM%2F7DGmz3S4sghN1Fro03EqsRwsnLuicwSWHa%2FiicKu6hyy6uc2CiRrnyjv3OWqb1oMG4bQTyxUabemc0bvkrevghu3o7uX6%2BleN%2FgI%3D&RelayState=https%3A%2F%2Fmysitesso.com

And this is how I believe the request should look like:
https://myidpurl,com/saml2/idp/SSOService.php?SAMLRequest=lVNNj9owEL3vr0C5k%2FCxgWJBJAr9QGUBkbSHXirjTDZWE9v1TBb239dJ2IWuVkj1JdL4zXvPbyZT5GVh2LyiXO3hTwVIdx13TmWhkDWXM6%2ByimmOEpniJSAjweL5w5oN%2FB4zVpMWuvDetN3u4ohgSWrVtq2WM2%2B7%2BbTeflltfo1E%2BGEIowmfwCg8ZOH9SIgwFJPJuJcNR4PhYHjg4ZCLtvUHWHQ8M8%2FRtpWd1U8yBbtxqjPvm1SphfSsg1jBSiFxRa6j1x93e%2BNuf5z0%2Buw%2BZP3Jzxa3dDFIxakhzokMsiCQqekW%2BlEqHwh8wSnnz4YLmUnhC10Gca4Bg%2FrtgxobxPE2BvskBfgmN6%2FemrQ%2BOldSPd4O6dCCkH1Nkl13t42TlmT%2BEt5CK6xKsGeZ7%2Fv1xW1mtaJCKkDU%2FlFS%2FrsNorHamuQCvahhnNYF1qRjo%2F9gKIF4yolPg2uCC6Vh9RBWy50upHhu6vX5rG3J6fbj64pMu1kDZaaeMhIo8l5Z5kWhjwsLnNyYyVbgdYJ%2FtM%2F7DGmz3S4sghN1Fro03EqsRwsnLuicwSWHa%2FiicKu6hyy6uc2CiRrnyjv3OWqb1oMG4bQTyxUabemc0bvkrevghu3o7uX6%2BleN%2FgI%3D&RelayState=https%3A%2F%2Fmysitesso.com&redirect_to=https%3A%2F%2Fmysitesso.com

Any thoughts?

**Comment by vdellangela** [comment]
According to the person in charge of the IDP, there is some missing information in the metadata.

The metadata should contain something like this:
"urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://idp-login.ete.cathaypacific.com/saml/idp/profile/redirectorpost/sso”

But I have no idea where to put this?
I'm actually digging into the onelogin plugin but there are many files that doesn't make my life easier haha

Any thoughts? Thx

**Comment by williamhector** [comment]
The underlying OneLogin library only supports the POST binding for ACS (login) as far as I know.
That could be the problem, if your IDP only supports Redirect ACS bindings.

This is my application's SAML metadata: https://www.typingtournament.com/api/saml2/metadata
The important line is: `<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://www.typingtournament.com/api/saml2/acs" index="1"/>`

That should be added to your metadata already if you have installed according to the instructions on the front page of this library.
It uses named routes to generate the URLs that get inserted into the SAML metadata, so if you want to change them, as we have, you need to add them to the file that contains your routes. Eg: 
// SAML
```
Route::group([ 'prefix' => '/saml2' ], function () {
	Route::get('/login/{idpId}', [ 'as' => 'saml_login',  'uses' => 'Auth\Saml2Controller@login' ]);
	Route::get('/logout',        [ 'as' => 'saml_logout', 'uses' => 'Auth\Saml2Controller@logout' ]);
	Route::get('/metadata', [ 'as' => 'saml_metadata', 'uses' => 'Auth\Saml2Controller@metadata' ]);
	Route::post('/acs',     [ 'as' => 'saml_acs',      'uses' => 'Auth\Saml2Controller@acs' ]);
	Route::get('/sls',      [ 'as' => 'saml_sls',      'uses' => 'Auth\Saml2Controller@sls' ]);
});
```
We use an "api" route group around everything, so the ACS path is `/api/saml2/acs` as mentioned in that XML element above.
(Note that the default saml_login route does not take an argument. We have just configured our service to use multiple IDPs)

Can you share your metadata url if still having problems?
