### ISSUE TITLE
Getting a 404

### ISSUE THREAD

**Issue by kadeprice** [aacotroneo/laravel-saml2#110]
I have done the composer install add the provider and alias. Then the php artisan vendor:publish and create the config file. At this point it doesn't matter if I leave it blank, or if I put in my SP info.

When I create a route like this to test
Route::get('sso', function(){
    Saml2::login();
});

And go to it all I get is a 404. It doesn't take me to onelogin. Just a 404
http://laravel.app/saml2/idp/SSOService.php?SAMLRequest=

This url works, and returns the meta data
http://laravel.app/saml2/metadata

**Comment by matijakovacevic** [comment]
in the config you have to put the IdentityProvider url for $idp_host

**Comment by kadeprice** [comment]
Thanks, with OneLogin, the url is different for the identity and the SSO, and SLO. So I had to just manually put them in for all of them.

**Comment by kadeprice** [comment]
Now I'm getting a  VerifyCsrfToken mismatch token error, but that's a laravel issue.

**Comment by gmartinez** [comment]
> Thanks, with OneLogin, the url is different for the identity and the SSO, and SLO. So I had to just manually put them in for all of them.

Hey, there I find myself at that very same place you were, reading the quoted comments I am not clear on what it is that one needs to "manually put". I thought you might remember and shed some light on it.

**Comment by adarshprakashprajapati** [comment]
I'm facing the same problem , can anybody help ..??
