### ISSUE TITLE
LoginEvent not being triggered

### ISSUE THREAD

**Issue by vdellangela** [aacotroneo/laravel-saml2#112]
Hi,

I'm trying to set up SSO with ADFS.

When I access my application, I'm getting the ADFS Login page.
However once logged in, I get redirected back to my application but the Event listener doesn't seem to get triggered and the website keeps looping between my application "URL/saml2/acs" and the login page of ADFS).

I've updated EventServiceProvider.php as below:
```
\Event::listen('Aacotroneo\Saml2\Events\Saml2LoginEvent', function (\Aacotroneo\Saml2\Events\Saml2LoginEvent $event) {
            Log::info('Saml2LoginEvent');
            dd($event);

            $user     = $event->getSaml2User();
            $userData = [
                'id'         => $user->getUserId(),
                'attributes' => $user->getAttributes(),
                'assertion'  => $user->getRawSamlAssertion(),
            ];
            $laravelUser = "";
            //if it does not exist create it and go on  or show an error message
            Auth::login($laravelUser);
        });
```

However I have no idea if this is correct, if this is suppose to get triggered like this or if I need to run a php command to start the listener? 
Also because this is a listener, am I going to be able to use the debug "dd" command?

Many thanks for your help

**Comment by axis80** [comment]
Hi @vdellangela.  I am having the same problem and I cannot seem to figure it out.  Do you remember what you did to solve it?

**Comment by vdellangela** [comment]
Hi @axis80, 

It was I believe a mix of different issues:
- my IDP entityId was using HTTP but my login and logout endpoints urls were using HTTPS. I had some difficulties to find this little detail but it was blocking the whole thing.
- also I don't know why but we couldn't make it work with a security SHA-2, so I had to change the NameIDFormat to 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified'
- in terms of security, I believe the only one required was 'authnRequestsSigned' => true

Also don't forget to add 'web' inside the 'routesMiddleware' at the top of the saml2_settings.php in order to save the session in the right place - otherwise it will keep looping between the IDP and your site.

Hope this helps!

**Comment by adydev15** [comment]
Hi @vdellangela 

I am also trying to configure SAML with ADFS on Premise which is on third party side.

I have same case where IDP's entity is with HTTP and other URL's are with HTTPS..so how did you resolved this .

Additionally right now IDP i am not getting reponse for after i try login in IDP as its response came with SAML with SAML Authrequest Not Signed . Any idea how that can be resolved ?

![image](https://user-images.githubusercontent.com/34705707/166672762-2a642a20-6eca-47c5-b447-d8c210df739d.png)
