### ISSUE TITLE
Saml2Controller->sls() doesn't fire Saml2LogoutEvent if application didn't initiate logout

### ISSUE THREAD

**Issue by samlev** [aacotroneo/laravel-saml2#12]
When the current application doesn't fire the logout event, the application receives `$_GET['SAMLRequest']` instead of `$_GET['SAMLResponse']`, which sends the OneLogin Saml2 library into a branch which redirects the user rather than returning:

```php
else if (isset($_GET) && isset($_GET['SAMLRequest'])) {
    if (!$logoutRequest->isValid($retrieveParametersFromServer)) {
        $this->_errors[] = 'invalid_logout_request';
        $this->_errorReason = $logoutRequest->getError();
    } else {
        // ...
        $this->redirectTo($this->getSLOurl(), $parameters);
    }
}
```

What this means is that the function never returns, and the logout event never fires, which means that the user's session doesn't actually get cleared.

I'm not sure what the best option is here - we can look for that `$_GET` variable and fire off the logout event early (although that has problems because we're not verifying the logout request before firing the event).

**Comment by aacotroneo** [comment]
I dont fully understand. But here is the big picture. sls() will be called by your IDP to notify your app that user logged out (It will redirect the user in fact, not an curl request). If format is correct this library fires an event so you can destroy local session. It can receive requests and responses.

A normal flow is you connect to your app A, and app B. If you logout from B, user will be redirected to A (sls()) with a *Request* and then to IDP to continue logout process. 
If you want to logout from A (your app), call ->logout(), that redirects to IPD and will eventually end up in sls() - but with a *Response*.

**Comment by samlev** [comment]
Ok, to explain better...

You have two apps, A and B, both logged in with the same IDP.

App A calls `logout()`, which contacts the IDP, and starts a logout request. The IDP calls each of the other applications (B) on their slo URL with `SAMLRequest`, and then returns to the requestiong application (A) with `SAMLResponse`

![Saml slo model](http://i0.wp.com/xacmlinfo.org/wp-content/uploads/2013/06/saml-logout.png)

The problem here is this:

When app B gets the `SAMLRequest`, and the OneLogin library redirects back to the IDP *before* the `LogoutEvent` is fired:

```php
class Saml2Controller extends Controller
{
    // ...
    public function sls()
    {
        $error = $this->saml2Auth->sls();
        if (!empty($error)) {
            throw new \Exception("Could not log out");
        }
        Event::fire(new Saml2LogoutEvent());
        return Redirect::to(Config::get('saml2::settings.logoutRoute')); //may be set a configurable default
    }
    // ...
}
class Saml2Auth
{
    // ...
    function sls()
    {
        $auth = $this->auth;

        $keep_local_session = true; //we don't touch session here
        $auth->processSLO($keep_local_session);

        $errors = $auth->getErrors();

        return $errors;
    }
    // ...
}

class OneLogin_Saml2_Auth
{
    //...
    public function processSLO($keepLocalSession = false, $requestId = null, $retrieveParametersFromServer = false)
    {
        $this->_errors = array();
        if (isset($_GET) && isset($_GET['SAMLResponse'])) {
            $logoutResponse = new OneLogin_Saml2_LogoutResponse($this->_settings, $_GET['SAMLResponse']);
            if (!$logoutResponse->isValid($requestId, $retrieveParametersFromServer)) {
                $this->_errors[] = 'invalid_logout_response';
                $this->_errorReason = $logoutResponse->getError();
            } else if ($logoutResponse->getStatus() !== OneLogin_Saml2_Constants::STATUS_SUCCESS) {
                $this->_errors[] = 'logout_not_success';
            } else {
                if (!$keepLocalSession) {
                    OneLogin_Saml2_Utils::deleteLocalSession();
                }
            }
        } else if (isset($_GET) && isset($_GET['SAMLRequest'])) {
            $logoutRequest = new OneLogin_Saml2_LogoutRequest($this->_settings, $_GET['SAMLRequest']);
            if (!$logoutRequest->isValid($retrieveParametersFromServer)) {
                $this->_errors[] = 'invalid_logout_request';
                $this->_errorReason = $logoutRequest->getError();
            } else {
                if (!$keepLocalSession) {
                    OneLogin_Saml2_Utils::deleteLocalSession();
                }
                $inResponseTo = OneLogin_Saml2_LogoutRequest::getID(gzinflate(base64_decode($_GET['SAMLRequest'])));
                $responseBuilder = new OneLogin_Saml2_LogoutResponse($this->_settings);
                $responseBuilder->build($inResponseTo);
                $logoutResponse = $responseBuilder->getResponse();

                $parameters = array('SAMLResponse' => $logoutResponse);
                if (isset($_GET['RelayState'])) {
                    $parameters['RelayState'] = $_GET['RelayState'];
                }

                $security = $this->_settings->getSecurityData();
                if (isset($security['logoutResponseSigned']) && $security['logoutResponseSigned']) {
                    $signature = $this->buildResponseSignature($logoutResponse, $parameters['RelayState']);
                    $parameters['SigAlg'] = XMLSecurityKey::RSA_SHA1;
                    $parameters['Signature'] = $signature;
                }

                $this->redirectTo($this->getSLOurl(), $parameters);
            }
        } else {
            $this->_errors[] = 'invalid_binding';
            throw new OneLogin_Saml2_Error(
                'SAML LogoutRequest/LogoutResponse not found. Only supported HTTP_REDIRECT Binding',
                OneLogin_Saml2_Error::SAML_LOGOUTMESSAGE_NOT_FOUND
            );
        }
    }
    // ...
}
```

The call path goes like this:

* **A** - initiate logout _request_
* **IDP** - receive logout _request_
* **IDB** - fire logout _request_ at **B**
* **B** - receive logout _request_:

```php
Saml2Controller->sls() {
    $error = $this->saml2Auth->sls() {
        $auth->processSLO($keep_local_session) {
            if (isset($_GET) && isset($_GET['SAMLRequest'])) {
                // check for errors in the request
                $this->redirectTo($this->getSLOurl(), $parameters);
            }
        }
    }
}
```

* **IDP** - fire logout _response_ at **A**
* **A** - receive logout _request_:

```php
Saml2Controller->sls() {
    $error = $this->saml2Auth->sls() {
        $auth->processSLO($keep_local_session) {
            if (isset($_GET) && isset($_GET['SAMLResponse'])) {
                // check for errors in the request
            }
        }
        // check for errors
        return $errors;
    }
    // check for errors
    Event::fire(new Saml2LogoutEvent());
    return Redirect::to(Config::get('saml2::settings.logoutRoute'));
}
```

So application B never receives the `Saml2LogoutEvent`, and the user's session is never cleared on application B.

**Comment by samlev** [comment]
Oh, and another side effect of this is that even if you change it to fire the logout event, the session isn't written if you call `processSLO` (because middleware handles writing the session, so the redirect inside the onelogin class means that the session never gets written)

**Comment by aacotroneo** [comment]
Oh, I got you! Events will be useless here, you are right! I used events to
decouple app logic from the generic controller... but as a workaround you
could use your own route for sls() and directly remove session directly.


2015-09-08 13:14 GMT-03:00 Samuel Levy <notifications@github.com>:

**Comment by samlev** [comment]
I've just sent a [pull request](https://github.com/onelogin/php-saml/pull/93) to the onelogin library, so that it will accept a callback to destroy the session. In that instance, we can trigger the logout event with a callback.

The only thing then is that the session still needs to be explicitly saved/written but... that can be up to the end project maintainer (seeing as they have to explicitly call `Auth::logout()` too).

**Comment by aacotroneo** [comment]
nice!! let's see what happens

2015-09-08 14:25 GMT-03:00 Samuel Levy <notifications@github.com>:

**Comment by aacotroneo** [comment]
Thank you!

2015-09-08 14:35 GMT-03:00 Alejandro Cotroneo <aacotroneo@gmail.com>:

**Comment by samlev** [comment]
one-login/php-saml has been updated to v2.6.1, which has the required change for this.

I've added PR #13 to update this library to use v2.6.1 of php-saml, and to bring the version number of this library up to 0.5.2

**Comment by aacotroneo** [comment]
Fix merged thanks!
