### ISSUE TITLE
"urn:oasis:names:tc:SAML:2.0:status:AuthnFailed

### ISSUE THREAD

**Issue by nijeshhirpara** [aacotroneo/laravel-saml2#120]
I am trying to configure SSO with Salesforce. I setup the IDP in salesforce from SP metadata. 
I am getting redirected to salesforce for login. After submitting form, I am getting back to my app https://sldm.wip/saml2/acs with 

array:2 [▼
  "code" => "urn:oasis:names:tc:SAML:2.0:status:AuthnFailed"
  "msg" => ""
]

Any help would be appreciated.

**Comment by nijeshhirpara** [comment]
I fixed this problem. This was due to salesforce. Even if I had administrator account, I had to manually enable my connected app from my profile. That was a missing part.

**Comment by anitalad28** [comment]
Hi,

I am facing same issue for okta IDP and simpleSAMLPHP. 
Can you please help me how I can fix it?
