### ISSUE TITLE
Read attributes

### ISSUE THREAD

**Issue by enricouniurb** [aacotroneo/laravel-saml2#136]
From the event Saml2LoginEvent 
is possible to read the attributesWithFriendlyName?
I would like to avoid the use of internal constant.

Thank you
Enrico

**Comment by enricouniurb** [comment]
I have added this code in the event listener:
      
  Event::listen('Aacotroneo\Saml2\Events\Saml2LoginEvent', function (Saml2LoginEvent $event) {
            $messageId = $event->getSaml2Auth()->getLastMessageId();
            // your own code preventing reuse of a $messageId to stop replay attacks

            //metter in file di configurazione 
            $attributesName = [
                'eduPersonEntitlement' => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.7',
                'cn' => 'urn:oid:2.5.4.3',                            
                'displayName' => 'urn:oid:2.16.840.1.113730.3.1.241',                
                'eduPersonOrgDN' => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.3',
                'pid' => 'urn:oid:2.5.4.10',
                'uid' => 'urn:oid:0.9.2342.19200300.100.1.1',
                'eduPersonScopedAffiliation' => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.9',
                'surname' => 'urn:oid:2.5.4.4',
                'schacHomeOrganization' => 'urn:oid:1.3.6.1.4.1.25178.1.2.9',
                'eduPersonPrincipalName' => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.6',
                'realm' => 'urn:oid:2.5.4.100',
                'eduPersonUniqueId' => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.13',
                'email' => 'urn:oid:0.9.2342.19200300.100.1.3',                 
            ];

            $user = $event->getSaml2User();
            $user->parseAttributes($attributesName);

**Comment by thierrymaasdam** [comment]
Ook een Laravel app aan het maken met een Entree Federatie koppeling? 😆
