### ISSUE TITLE
will this work with OKTA?

### ISSUE THREAD

**Issue by VickG** [aacotroneo/laravel-saml2#15]
I am trying to integrate with https://www.okta.com/

Can I use this library for that purpose?

**Comment by aacotroneo** [comment]
I dont know. This is just a Laravel wrapper for https://github.com/onelogin/php-saml. It they do, we do.

**Comment by bronxct1** [comment]
@VickG Yes this will work with OKTA, I have implemented this in a project quite easily

**Comment by aacotroneo** [comment]
thanks @bronxct1 for helping out!

**Comment by narbehmovsesi** [comment]
@bronxct1 can you share an example?

**Comment by bronxct1** [comment]
I'll have to check if I still have an example. I left the company where I implemented this, but it was quite straightforward after following the initial set up. Basically in the Saml2Listener you will grab the saml user and log them into the Laravel application.

I would be glad to help you out if you are in the Laravel slack

**Comment by durancu** [comment]
Hi @bronxct1! Did you find your example? I'm working on this stuff next week an would be good to have an starting point from your experience. Best regards

**Comment by bronxct1** [comment]
```php
    /**
     * Handle the event.
     *
     * @param  Saml2LoginEvent  $event
     * @return void
     */
    public function handle(Saml2LoginEvent $event)
    {
        $saml_user = $event->getSaml2User();

        $user = Contributors::where('username', '=', $saml_user->getUserId())->first();

        $attributes = $user->getAttributes();

        if (empty($user)) {
            $user = Contributors::create([
                'username' => $user->getUserId(),
                'email' => $user->getUserId(),
                'first_name' => $attributes['first_name'][0],
                'last_name' => $attributes['last_name'][0]
            ]);

            $user->base()->create([
                'slug' => $user->full_name
            ]);
        }

        if (is_null($user->base)) {
            $user->base()->create([
                'slug' => $user->full_name
            ]);
        }

        if (!$user->hasRole($attributes['role'][0])) {
            $role = Role::where('name', $attributes['role'][0])->first();

            $user->roles()->sync([$role->id]);
        }

        $this->auth->login($user);
    }
```

**Comment by durancu** [comment]
Thank you @bronxct1. I will check it out!

**Comment by durancu** [comment]
Sorry, it this code to replace the vendor listener handle function? I'm not sure where it goes.

**Comment by chaseconey** [comment]
This has been implemented into the Socialite community package:
http://socialiteproviders.github.io/providers/okta/
