### ISSUE TITLE
InvalidNameIDPolicy

### ISSUE THREAD

**Issue by neomaximus2k** [aacotroneo/laravel-saml2#157]
I am attempting to implement this code with ADFS for SSO.

The user clicks the button which takes them to the built in route (/saml2/login) which then talks to ADFS, the ADFS talks back to the ACS however I then get reidrected to the error page and the following line appears in the laravel log

Saml2 error_detail {"error":"The status code of the Response was not Success, was Requester -&gt; urn:oasis:names:tc:SAML:2.0:status:InvalidNameIDPolicy"} 

Any ideas?

**Comment by neomaximus2k** [comment]
Fixed it :)

**Comment by julienmonty** [comment]
Hi @neomaximus2k,

Same issue here, could you share how you fixed this problem, please ?

**Comment by MoiseScalzo** [comment]
@neomaximus2k could you please share the fix?

**Comment by adydev15** [comment]
Hi @julienmonty @neomaximus2k 

Though it is too old but in case if anyone stuck with issue with same as i was 

NameIDFormat in your IDP Settings should be :
urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified

This will help hopefully.

Though i have additional issue here after this it should handle the SAML response in Service Provider to extract claims but it isnt working that way if anyone knows then would be helpful.
