### ISSUE TITLE
Upgrade to OneLogin's SAML PHP Toolkit v3.0.0

### ISSUE THREAD

**Issue by perifer** [aacotroneo/laravel-saml2#159]
v3.0 of OneLogin SAML PHP Toolkit is released and removes dependency on mcrypt.

Any plans on upgrading?

**Comment by aacotroneo** [comment]
I don't have plans to upgrade it myself - I don't have the time. here's another related thread https://github.com/aacotroneo/laravel-saml2/issues/122

**Comment by perifer** [comment]
Thanks!
