### ISSUE TITLE
Better documentation or tutorial

### ISSUE THREAD

**Issue by dnsimmons** [aacotroneo/laravel-saml2#17]
Would it be possible for you to create a full tutorial on implementing a generic sign on for Laravel 5 ?
Or better documentation on the methods available in the package and how to use them?

New to SAML here ... proving very confusing. Any help would be appreciated.

**Comment by aacotroneo** [comment]
hi! saml is a complex thing! this library is a wrapper for onelogin. I recommed that you start there and try to make a connection to your idp. Then you'll find that this library just makes appropriate calls to oneling within Laravel framework.
https://github.com/onelogin/php-saml#sp-setup

Note that this is only a SP part, you need an IPD to connect to.

**Comment by pitbulk** [comment]
http://samltool.com/ is a site where you can start learning SAML.

Or if you need a simple explanation: https://github.com/jch/saml
