### ISSUE TITLE
Where to put listen Aacotroneo\Saml2\Events\Saml2LoginEvent?

### ISSUE THREAD

**Issue by anhhh11** [aacotroneo/laravel-saml2#18]
I'm trying to user laravel-saml2 with OpenAM but after login it ran in to endless loop. I think maybe because of `Saml2LoginEvent` is not listened at the right point. I've tried to add it in `route.php`, in middlware after 'StartSession` but it doesn't work.
http://localhost:8080/openam/XUI/#login/&realm=/&forward=true&spEntityID=http://lavapp.dev/saml2/metadata&goto=/SSORedirect/metaAlias/idp?ReqID=ONELOGIN_69bdcea5602172fa91feff7e67ecd06999c0ae37&index=null&acsURL=http://lavapp.dev/saml2/acs&spEntityID=http://lavapp.dev/saml2/metadata&binding=urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST&AMAuthCookie=

**Comment by aacotroneo** [comment]
that's purely Laravel stuff.. For L5 you have some `EventServiceProvider` where you will add the class that listens for the event. Check here https://laravel.com/docs/master/events#registering-events-and-listeners.
That's pretty much the problem, if that event is not listened, your session is not saved, so the auth middleware redirects back again to login.

**Comment by anhhh11** [comment]
I've found problem with session, laravel 5.2 it doesn't use StartSession middlware by default, but laravel-saml2 imply that session has started => lost login & redirect loop. So, my current solution is to group routes in laravel-saml2 to `web` middleware(that having StartSession).
