### ISSUE TITLE
SLO without LogoutRequest?

### ISSUE THREAD

**Issue by DanielMalmgren** [aacotroneo/laravel-saml2#180]
I'm trying to get single log out working between my application (using laravel-saml2) and my IdP. A SP is supposed to simply call /wa/logout on the IdP to initiate SLO. However, if the SP also adds a LogoutRequest (as laravel-saml2 does) the IdP completely bails out, giving me a http 500.

So what I need is for laravel-saml2 to simply call my configured singleLogoutService URL upon logout without adding anything more (no arguments) to the URL. Would that be possible? If not, would it be considered a sane feature request to add an option for this?

**Comment by aacotroneo** [comment]
check the readme https://github.com/aacotroneo/laravel-saml2#log-out 
I assume /wa/logout is not part of the saml2 standard, so this library has nothing to do with it. Call it however you like, IDP will notify your SP when the session is closed - if you don't call this lib logout, it won't send any logout request

**Comment by DanielMalmgren** [comment]
I think you are misunderstanding me. This is a logout initiated from the SP (ie from my Laravel app which is using laravel-saml2). Ie the first scenario in the readme, I want the SP to notify the IdP about the logout.

I have set the singleLogoutService url in saml2_settings.php to the URL that my IdP wants, which is "/wa/logout". This works in the sense that when I log out of my Laravel app it makes a call to the URL at the IdP. However it appends the call with "?SAMLRequest=..." which makes the IdP utterly unhappy, so I'm just wondering if theres any way of making it NOT do this and just call the url without any arguments whatsoever. Clearer?

**Comment by aacotroneo** [comment]
I got that part... but you can't initiate a SAML logout without a SAMLRequest. It's the way the IDP validates auth. Not sure if want a different binding, or what is it that your endpoint expects if it doesn't need a SamlRequest.

**Comment by aacotroneo** [comment]
if you don't need SAML parameters at all, why use this library... redirect the user to that endpoint directly? 🤷‍♂️

**Comment by DanielMalmgren** [comment]
Hmmm... Obviously this IdP doesn't need any auth for logging out, only for logging in. Never thought of it as a problem before. But now that you say it, it's kinda weird if it doesn't accept LogoutRequests. Gotta check that with the product support for the IdP.

But I guess you're right, I could simply redirect the user to the IdP's logout URL. Feels a bit like a workaround rather than solution, but I guess it'd work. I'm closing this ticket. Thanks for your help!
