### ISSUE TITLE
Get user if it´s logged in yet?

### ISSUE THREAD

**Issue by Albvadi** [aacotroneo/laravel-saml2#184]
Hi,
It´s possible to get user info if the user it´s authenticated yet with the IdP outside the app?

Steps:
1.- User login in the  IdP in one browser tab.
2.- After succesfull login, the user enter in a protected route in the app.

Current behavior:
The app redirect to IdP login again.

Expected behavior:
The user is logged yet, so, enter in the protected route.

Thanks!

**Comment by Albvadi** [comment]
All is working as expected....
Sorry!

**Comment by adydev15** [comment]
Hi @Albvadi 

i am having same issue can you please guide me how can i achieve that .

In my case i want to check if user has already logged in IDP then i need to redirect user to homepage.
