### ISSUE TITLE
Logout always return `Could not log out`

### ISSUE THREAD

**Issue by anhhh11** [aacotroneo/laravel-saml2#19]
When logging out, app redirect URL to /saml2/logout (or Saml2Controller@logout), but it always return `Could not log out`.
I've tried:
  Event::listen('Aacotroneo\Saml2\Events\Saml2LogoutEvent', function ($event) {
            Auth::logout();
            Session::save();
        });

**Comment by aacotroneo** [comment]
oh, It seems I forgot to print the error. Try to put a `Log::error('Saml2 logout error', $error);` on this line, so we have more info on what's happening.
https://github.com/aacotroneo/laravel-saml2/blob/c9e69c5604ad947d41b3ae99037aae555423aa8e/src/Aacotroneo/Saml2/Http/Controllers/Saml2Controller.php#L81
