### ISSUE TITLE
route:list produces 404 from the Saml2Controller

### ISSUE THREAD

**Issue by xnasa** [aacotroneo/laravel-saml2#193]
laravel_saml2 : 2.0.0
Laravel 5.8

The application routes used in the url seem to work correctly however the command
 ```
php artisan route:list
```
produces and error with a 404 exception.
```
$ php artisan route:list

   Symfony\Component\HttpKernel\Exception\NotFoundHttpException  :

  at {_project path_}\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:992
    988|      */
    989|     public function abort($code, $message = '', array $headers = [])
    990|     {
    991|         if ($code == 404) {
  > 992|             throw new NotFoundHttpException($message);
    993|         }
    994|
    995|         throw new HttpException($code, $message, null, $headers);
    996|     }

  Exception trace:

  1   Illuminate\Foundation\Application::abort("", [])
      {_project path_}\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php:46

  2   abort()
      {_project path_}\vendor\aacotroneo\laravel-saml2\src\Aacotroneo\Saml2\Http\Controllers\Saml2Controller.php:24

```
It appears that the Saml2Controller evaluates to false when the command 'php artisan route:list' tries to produce information on the routes. Other than that the controller operates the route in the web interface just fine.

**Comment by LauLogisch** [comment]
Same issue

**Comment by aloha** [comment]
+1 on the 404.  It'd be a better fix if it didn't need request parameters within the class constructor and instead looked to inject dependencies using Laravel's IoC.

**Comment by danmichaelo** [comment]
Agree. In general, I think it's best to avoid constructors in controllers altogether if possible.
