### ISSUE TITLE
NoAuthnContext

### ISSUE THREAD

**Issue by nisaac2fly** [aacotroneo/laravel-saml2#2]
I am not all that familiar with SAML so bare with me. 

I just installed this package in a new instance of Laravel 5. Unfortunately I am getting this error `The status code of the Response was not Success, was Responder -> urn:oasis:names:tc:SAML:2.0:status:NoAuthnContext`.

Any thoughts on how what this error means? 

By the way I am connecting to ADFS and not PHPSimpleSaml as the IDP.

I would appreciate any suggestions. Thanks.

**Comment by aacotroneo** [comment]
I havent used ADFS, but it seems that is a configuration problem there. Is there any way to test if ADFS is working on its own? e.g Simplesamlphp has a sample login that works out of the box.

**Comment by nisaac2fly** [comment]
@aacotroneo I'm sure it is a configuration problem. The problem is I don't know how to figure out where the problem is (if it is through the ADFS server or the OneLogin configuration). I do have an installation of the phpsimplesaml connecting properly to the ADFS server and I have tried to compare the configuration phpsimplesaml and the onelogin package but haven't been able to figure out what the difference is.

**Comment by pitbulk** [comment]
Moved the thread here: https://github.com/onelogin/php-saml/issues/62
