### ISSUE TITLE
Laravel 6?

### ISSUE THREAD

**Issue by mholmes-hs** [aacotroneo/laravel-saml2#200]
Has anyone tried this with Laravel 6.0?

**Comment by mvs-fmts** [comment]
I've been using v2.0.0 with Laravel 6.0 for a few weeks now and didn't have to make any code or config changes.

**Comment by mholmes-hs** [comment]
Great thanks for the info.  Just got a new laptop and not set up yet.  Project is starting next week, this will make estimating easier.
