### ISSUE TITLE
POST and Redirect method

### ISSUE THREAD

**Issue by FlorianB385** [aacotroneo/laravel-saml2#206]
Is it possible to use "POST and Redirect" method from PingFederate?
https://documentation.pingidentity.com/pingfederate/pf84/#gettingStartedGuide/task/spInitiatedSsoRedirectPost.html

**Comment by rlcurrall** [comment]
If I understand correctly you are wanting to have a SP initiated login?

This package does provide an endpoint that achieves this in the [`routes.php`](https://github.com/aacotroneo/laravel-saml2/blob/master/src/routes.php) file, the `saml2_login` route. When the user makes a get request to this route (i.e. navigating to `http://myapp.com/saml2/some-idp/login` in the browser) they will be **redirected** to the IdP. After logging into the IdP they will be sent back to the SP via a **POST** request.

**Comment by FlorianB385** [comment]
ok, thank you!
