### ISSUE TITLE
Settings file not found

### ISSUE THREAD

**Issue by enterlight** [aacotroneo/laravel-saml2#208]
I installed and followed the instructions.  I am running into this:

umen.ERROR: OneLogin\Saml2\Error: Settings file not found: /app/src/vendor/onelogin/php-saml/settings.php in /app/src/vendor/onelogin/php-saml/src/Saml2/Settings.php:309

**Comment by v1lling** [comment]
I'm having the same issue. 
Can you tell me how you resolved this?
Thanks!
