### ISSUE TITLE
Error in OneLogin SAML Util.php

### ISSUE THREAD

**Issue by acutting1755** [aacotroneo/laravel-saml2#22]
I have configured this per the instructions included in the readme.md.  However when I attempt to go to /saml2/metadata I get PHP Fatal error:  'continue' not in the 'loop' or 'switch' context in /app/vendor/onelogin/php-saml/lib/Saml2/Utils.php on line 1006.  For reference I am using V0.6.0

**Comment by aacotroneo** [comment]
seems a PHP 7 error... 
also from the library we wrap here. The error is fixed, but still in master (no release)
https://github.com/onelogin/php-saml/issues/98

we should update our composer.json when onelogins gets to support php 7

**Comment by acutting1755** [comment]
you beat me to it! I just confirmed it is a PHP7 issue.  I have reverted my version back to PHP 5.6.* in my composer file to make sure this is not an issue for now.  Thank you for looking into this so quickly.

**Comment by pitbulk** [comment]
[php-saml v2.7.0](https://github.com/onelogin/php-saml/releases/tag/v2.7.0) fixed that.
I think you can close that issue now.
