### ISSUE TITLE
Redirect back after logout

### ISSUE THREAD

**Issue by sakaye** [aacotroneo/laravel-saml2#241]
Hello, I have saml authentication working in my app but when a user logs out they end up on my Idp logout page. How can I get them back to the original site? Am I just missing something in the docs? Thanks for the help.

Bryun

**Comment by mohanrvgit** [comment]
Hi 

Did you solve the idp logout page issue?

**Comment by sakaye** [comment]
I did not. I believe it has to do with configurations on our SAML controller. I told my end users to just deal with it.
