### ISSUE TITLE
Saml2 error - invalid response 

### ISSUE THREAD

**Issue by Palak28** [aacotroneo/laravel-saml2#243]
Hello, I have used saml2 package in my laravel admin panel. I have configured the settings according to the instructions. But when I click on login button, its successfully logged on in my idp account, but in response to my application, its causing invalid response error in saml2/test/acs. The error format is "The response was received at https://www.example.com/saml2/test/acs instead of https://www.example.com:3344/saml2/test/acs" where https://www.example.com:3344/saml2/test/acs is defined in my .env file. Can anyone help me?

**Comment by Palak28** [comment]
Got the solution, it was configuration port issue.... set the base_url and its working.!!

**Comment by msassa** [comment]
Hi @Palak28 I have the same issue with an application in aws behind a load balancer. Can you explain how you solve this problem, please? Where you define base_url. Thanks.

**Comment by lcue** [comment]
Hi @msassa,

In the file /config/saml2/[name idp]_idp_settings.php
above 'debug' => env('APP_DEBUG', true),

add
'baseurl' => env('APP_URL'),
