### ISSUE TITLE
Suggestion: Remove input related functions from Saml2User

### ISSUE THREAD

**Issue by beeglebug** [aacotroneo/laravel-saml2#27]
Just a suggestion, but I think that the User object shouldn't really be responsible for dealing with input from the request.

I'm thinking of making an MR which moves this responsibility out, so that the controller does the `getIntendedUrl` logic internally, and moving the `getRawSamlAssertation` onto the `Saml2LoginEvent` so it can still be accessed by the parent application.

My only worry is that this would be a breaking change to the previous versions, but if you are happy with that I think it sticks to the Single Responsibility Principle a bit more.

**Comment by aacotroneo** [comment]
Single responsibility is a long thread...  a good principle to follow, but it also depends on the level of abstraction... ie. I could make a single class called 'laravel-saml2' which has a single responsibility at that level.  
For our case, maintainability is not an issue. We can always refactor later when we know what to extend... and API is 'simple' now. Now the user is like our most important 'api'. It's not a 'user', but it's a thing which gives you a very simple interface to saml with 4 methods. If we move that logic into the controller it will be harder to share with our users, and/or we need to introduce new entities (which add complexity).

**Comment by beeglebug** [comment]
I agree completely with not adding extra complexity, which is why I thought we could just move the two functions which are concerned with the request input onto the Saml2LoginEvent (and inject the request into it alongside the user object). That way the code consuming the event still gets access to the same functions, just a couple of them move to the other object. 

I might make the change and send the pull request just so you can see what I mean, but feel free to ignore it, it's your library after all (and it is quite a fussy change tbh).
