### ISSUE TITLE
 class 'aacotroneo\sam2\saml2serviceprovider' not found 

### ISSUE THREAD

**Issue by razazaidisd** [aacotroneo/laravel-saml2#3]
I am new to the Laravel world!
I am trying to configure this Library in Laravel 5, I setup a dummy laravel application and followed your provided steps. But when I execute the below command then everything went wrong
php artisan config:publish aacotroneo/laravel-saml2 

" [Symfony\Component\Debug\Exception\FatalErrorException]
class 'aacotroneo\sam2\saml2serviceprovider' not found "

Can you please help me, what I missed? 
or this configuration steps is for Laravel 4 as mentioned in the "Installation - Composer" description.

Thanks in advance.

**Comment by aacotroneo** [comment]
yeah, sorry about that.. I think you are right. Does simply 'php artisan config:publish' work?

**Comment by razazaidisd** [comment]
Yeah that configuration steps was for laravel 4, well I just resolved that two hours before, thanks.

Also need to ask one more thing. Can you please help me in Configuration
"You need to configure your sp and IDP (remote server)" , should I have to write my own IDP or Laravel already provided me in the package.
My question is how can I configure SP and IDP in LARAVEL?

**Comment by aacotroneo** [comment]
This library just acts as an SP. IDPs (Saml Identity providers) are quite huge beasts. Generally you set up an IDP in your infrastructure which handles all your domain users and authentication, and then the other apps just act as simple service providers that delegate authentication to the IDP.
For PHP you have simplesamlphp, but it has a its learning curve... The SP configuration will totally depend on you IDP configuration

**Comment by aacotroneo** [comment]
close inactive
