### ISSUE TITLE
Helper function misusage on Saml2User.php

### ISSUE THREAD

**Issue by ozkankirik** [aacotroneo/laravel-saml2#31]
With 0d5412d commit, Saml2User.php became broken.
While replacing facade usages with helper function,  url() helper function misused.
url() helper function returns string, so that url()->full() usage is wrong

**Comment by aacotroneo** [comment]
is it throwing any error, and/or which version are you running. It _should_ work on Laravel 5.2 

https://laravel.com/docs/5.2/helpers#method-url

**Comment by ozkankirik** [comment]
Hi, 

I'm using Laravel 5.1 LTS, It throws error while checking RelayState after Login Event.
https://laravel.com/docs/5.1/helpers#method-url 
Laravel 5.2 returns UrlGenerator instance but, Laravel 5.1 return string.
