### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by cby016** [aacotroneo/laravel-saml2#35]
We would like to use this package on a project we are developing however one of the requirements is the user enters his/her credentials on our site and we send them over to the idp. Would this package work for that? 

Also we are using laravel 4.2.7 could we install this package on that version or would we have to upgrade to 5.x? If we do need to upgrade, which version would be best to use 5.0 or 5.1?

**Comment by pitbulk** [comment]
```
the user enters his/her credentials on our site and we send them over to the idp
```
This is not how SAML works, so you can't use this package that provides SAML support.
