### ISSUE TITLE
Exposing OneLogin_Saml2_Auth->getLastErrorReason()

### ISSUE THREAD

**Issue by Czachur** [aacotroneo/laravel-saml2#38]
Hey @aacotroneo ,

Would you be able to create a public method in Saml2Auth.php to expose OneLogin_Saml2_Auth->getLastErrorReason(). I can create a PR if you want.

Nathan.

**Comment by aacotroneo** [comment]
I think a PR for that would be nice (I cant test the code myself right now). We could just expose the hole object just in case... `getOneLoginSaml2Auth()` that returns auth?

**Comment by Czachur** [comment]
That is a good suggestion!

Another idea would be to have Saml2Auth extend OneLogin_Saml2_Auth, then Saml2Auth would have access to the public methods in OneLogin_Saml2_Auth (Also meaning you could remove Saml2Auth->isAuthenticated(), Saml2Auth->login() and Saml2Auth->logout()) . Can you see any issues with this inheritance?

**Comment by aacotroneo** [comment]
Inheritance adds a little more of coupling.. if onelogin changes their api in the future, we change our implementation and our users will be safe. 
I didnt expose the raw object initially to have a clean API and easy to use for _regular_ users, but I understand that for some advanced cases is needed... Its not clean, but its needed.. I would just expose the object for advanced usage and leave the rest of the api like it is.

**Comment by pitbulk** [comment]
Hi @aacotroneo, I try to maintain the API methods of php-saml intact, but sometimes new functionalities require adding new parameters or implement new methods.
For new releases, I will try to document what API methods changed so will be easy for you to update your part.

Best regards.

**Comment by aacotroneo** [comment]
hi @pitbulk, I know that, I was just commenting a general idea about inheritance over composition, your API has been very stable for sure.. we barely had to change anything because of a breaking change here
BTW, very nice library you've made!
Cheers!
