### ISSUE TITLE
Just to ask a question

### ISSUE THREAD

**Issue by romantico** [aacotroneo/laravel-saml2#4]
Can i use this as a SP for developing laravel where im using azure ad as my IDP... hoping for reply !!

**Comment by romantico** [comment]
php artisan config:publish is not working ''invalidargumentexception''

**Comment by aacotroneo** [comment]
'php artisan config:publish' should work (laravel 5). 
And for the other question, you should really ask here: [https://github.com/onelogin/php-saml](onelogin) as this library just helps to set that up in laravel

**Comment by romantico** [comment]
'php artisan vendor:publish' i used instead 'php artisan config:publish' bro and it's successfully wrote saml2_settings on \config\saml2_settings.. is that the same?

**Comment by aacotroneo** [comment]
Oh yes!! you are totally right!! sorry about that. I'll fix the docs!

**Comment by romantico** [comment]
no problem bro.!!  i am only an amature in laravel .... meanwhile i had already tried  the demo on onelogin\php-saml  i am meeting some issues but i successfully get the response azure.. and no problem on setting the idp ... now im wondering how i can set  sp section using you aacotroneo/laravel-saml2 ... in onelogin\php-saml  demo the sp settings  looks this
 
        'sp' => array (
	

          //  'entityId' => $spBaseUrl.'/demo1/metadata.php',
           'entityId' => 'http://localhost/myapp',

             'assertionConsumerService' => array (
                'url' => $spBaseUrl.'/demo1/index.php?acs',

				            'binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
                       
            ),
            'singleLogoutService' => array (
                'url' => $spBaseUrl.'/demo1/index.php?sls',
			            'binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',

            ),

what is the equavalent settings now in config/saml2_settings.php??
 thanks in advance.

**Comment by romantico** [comment]
this library is very much useful .. ill tell my friends and co developers to check this out.

**Comment by romantico** [comment]
which specific file should i call Saml2Auth::login()?

**Comment by aacotroneo** [comment]
yes, you have all the detail in the docs (https://github.com/aacotroneo/laravel-saml2#usage)

**Comment by aacotroneo** [comment]
close inactive
