### ISSUE TITLE
Update php-saml to 2.9.0

### ISSUE THREAD

**Issue by pitbulk** [aacotroneo/laravel-saml2#42]
php-saml [2.9.0](https://github.com/onelogin/php-saml/releases/tag/v2.9.0) version includes security improvements so I recommend to use it.

**Comment by olivM** [comment]
+1  => it also allow compatibility with PHP7

**Comment by aacotroneo** [comment]
sorry, I don't have the time right now.. but I'd accept a PR.

Let's bump the version so it doesn't have to be BC.

**Comment by pitbulk** [comment]
I think there is no compatibility issues between 2.6.0 and 2.9.0 so you only need to change the [composer definition](https://github.com/aacotroneo/laravel-saml2/blob/master/composer.json#L17)

**Comment by olivM** [comment]
i made the pull request : https://github.com/aacotroneo/laravel-saml2/pull/46

**Comment by aacotroneo** [comment]
thanks guys.. here is the new release (0.8.0) https://github.com/aacotroneo/laravel-saml2/releases/tag/0.8.0

**Comment by camstorrs** [comment]
I'm receiving the following error when tring to install laravel-saml2 via composer 

Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for aacotroneo/laravel-saml2 ^0.8.0 -> satisfiable by aacotroneo/laravel-saml2[0.8.0].
    - aacotroneo/laravel-saml2 0.8.0 requires onelogin/php-saml 2.9.1 -> satisfiable by onelogin/php-saml[2.9.1] but these conflict with your requirements or minimum-stability.

I have onelogin/php-saml 2.10.2 installed
