### ISSUE TITLE
Custom saml call after login

### ISSUE THREAD

**Issue by cby016** [aacotroneo/laravel-saml2#43]
Is it possible to execute a custom SAML call after the user has logged in? I was thinking of dynamically changing the settings returned by saml2_settings.php and then call the Saml2::login() function again. Is that the best way to accomplish this or is there a better way?

**Comment by aacotroneo** [comment]
yes.. it seems you can do that and saml2_settings can run code too! May be you wont find the best place to do so within this library, as it's mostly a wrapper that makes calls at appropriate times.. all it does is helping to implement a typical SSO flow. But if you find the hook to create your extra call, there shouldnt be a problem.

**Comment by cby016** [comment]
The problem I'm running into is that I need to access the laravel session in the saml2_settings.php file and it's throwing an error. It seems that saml2_settings.php is run before the session middleware. Is there any way to pass data to the saml2_settings.php file or set a global variable before it is executed?

**Comment by cby016** [comment]
I got this working by editing the saml2_settings.php file and reading the PHP $_SERVER variable to know which settings to return.
