### ISSUE TITLE
Unable to run php artisan vendor:publish

### ISSUE THREAD

**Issue by wwendorf** [aacotroneo/laravel-saml2#44]
The command doesn't appear in the php artisan list, and I tried to run clear-compiled and dump-autoload to no avail as well.

Can I just insert that config file in the location the docs showed?

Wade

**Comment by jmandrade** [comment]
What version of Laravel are you using? vendor:publish is for Laravel 5.

Do you have config:publish? that's Laravel 4. Laravel-saml2 is "A Laravel 5 package"

**Comment by rajkumarsakthivel** [comment]
Any one guide me how to use this package for laravel 4:

step :1) To install Saml2 as a Composer package to be used with Laravel 4, simply add this to your composer.json:

"aacotroneo/laravel-saml2": "*"

step :2) composer update

step :3)  app/config/app.php in the providers array. If you want, you can add the alias saml2:

'providers' => [
        ...
        'Aacotroneo\Saml2\Saml2ServiceProvider',
]

'alias' => [
        ...
        'Saml2'     => 'Aacotroneo\Saml2\Facades\Saml2Auth'

Step :4) what is next step ????

Note: I am new for using this package

**Comment by rajkumarsakthivel** [comment]
laravel 4 we need to use like : php artisan config:publish  aacotroneo/laravel-saml2

**Comment by Jameron** [comment]
One more thing to add, the vendor publish command is not publishing the config file. Also in Laravel 5+, the config path is no longer ```app/Config```, it is now ```config/```. I was able to copy the saml2_settings.php file located at ```vendor/aacotroneo/laravel-saml2/src/config/``` to my config folder.
