### ISSUE TITLE
Cannot set an arbitrary string as sp identifier

### ISSUE THREAD

**Issue by peetersdiet** [aacotroneo/laravel-saml2#45]
Assuming the SAML2 authentication uses a metadata.xml, the sp entityId automatically sets the entityId to the saml_metadata route, but the use of the metadata.xml should be optional.

When not using a metadata.xml, an sp entityId URI can be chosen at will, as long as it matches the configured entityId on the idp. At my client the entityId is simply a domain name (without scheme).

As a solution, I propose adding an empty-check on the config-value when setting the sp entityId. [Line 45 in the Saml2ServiceProvider class](https://github.com/aacotroneo/laravel-saml2/blob/master/src/Aacotroneo/Saml2/Saml2ServiceProvider.php#L45) would be changed to:
```php
$config['sp']['entityId'] = empty($config['sp']['entityId']) ? URL::route('saml_metadata') : $config['sp']['entityId'];
```

If it's is ok, I'll create a PR to apply the change.

**Comment by thesupad** [comment]
I support this change as our client is in the same situation and asked us to give them sp id prior work actually was started

**Comment by pitbulk** [comment]
Im the php-saml developer and Im agree with that solution.

**Comment by aacotroneo** [comment]
If the author agrees, then I agree too! The PR will be appreciated!

**Comment by peetersdiet** [comment]
Wanted to create the PR, but seems the change was already applied yesterday in PR #56 .

Closing
