### ISSUE TITLE
Adding <ds:Signature> data to AuthnRequest

### ISSUE THREAD

**Issue by ddrdusan** [aacotroneo/laravel-saml2#47]
The IdP I use requires this data. I've tried a lot of different settings values & combinations, but neither resulted in signature being included in the samlp::AuthnRequest. Is it possible?

**Comment by aacotroneo** [comment]
you better ask at onelogin issuses.. this library is mainly a wrapper to integrate it to Laravel

**Comment by ddrdusan** [comment]
ok, tnx. the issue re-opened at https://github.com/onelogin/php-saml/issues/142

**Comment by pitbulk** [comment]
I think you can close it
