### ISSUE TITLE
local.ERROR: Saml2 error ["invalid_response"] 

### ISSUE THREAD

**Issue by dbeyzad** [aacotroneo/laravel-saml2#49]
I am receiving the following in the laravel log after the SAML is returned from the IDP. In chrome using the SAML inspector tool everything looks fine.

No login event is fired within laravel.

Any suggestions?

Thank you

**Comment by aacotroneo** [comment]
you can dive into the source... that error is in onelogin dep
https://github.com/onelogin/php-saml/blob/cd7ced0dc23a47dc57b81134ff94d4b7fef57099/lib/Saml2/Auth.php#L133

use a debugger or a classy var_dump and trace this https://github.com/onelogin/php-saml/blob/7a87f05681c57d121b2da81768532ab7197b1a84/lib/Saml2/Response.php#L85

**Comment by dbeyzad** [comment]
@aacotroneo  Thanks. I managed to fix it, it was a certificate issue.
I have this fully working now with laravel 5.3

**Comment by pkendre** [comment]
HI,

I am facing the same issue. What is the certificate issue? can you please explain in details, so that I may get some clue

**Comment by pkendre** [comment]
Hi, Finally I have resolved this issue.

The "x509cert" from idp configuration in saml2_settings.php was not matching with the IDP server crt. I copied the IDP .crt content to the x509cert variable and it worked :)
