### ISSUE TITLE
error in entegrating the library in laravel 5

### ISSUE THREAD

**Issue by rendhon** [aacotroneo/laravel-saml2#6]

**Comment by rendhon** [comment]
Class 'Aacotroneo\Saml2\Facades\Facade' not found having this error in laravel 5
after

adding "aacotroneo/laravel-saml2": "*" in my composer.json and updated already
*already added
'providers' => [
...
'Aacotroneo\Saml2\Saml2ServiceProvider',
]

'alias' => [
...
'Saml2' => 'Aacotroneo\Saml2\Facades\Saml2Auth',
]

*created a controller with codes :
<?php namespace App\Http\Controllers;

use Aacotroneo\Saml2\Facades\Saml2Auth;

class myController extends Controller {

public function index()
{

   Saml2Auth::login();

}
}

thnx..!

**Comment by aacotroneo** [comment]
You don't need to include the alias if you are not using it. As you are accessing the Facade directly, you should use php namespaces (prefix it with the inverted slash - \Saml2Auth::login();). The alias alternative is to put a 'use Saml2' and call 'Saml2::login()'

If that's not the problem, provide the full stack.
Cheers!!

**Comment by rendhon** [comment]
aah? therefore ... something wrong in my controller??  can you please edit that controller for me? i'm new here in laravel 5 .. thx for bearing with me.

**Comment by aacotroneo** [comment]
just modify the index(). Add a back-slash to the call and see if it works. You don't need to add the 'alias' entry.
```php
use Aacotroneo\Saml2\Facades\Saml2Auth;
class myController extends Controller {
   public function index()
   {
       \Saml2Auth::login();
   }
}
```

**Comment by rendhon** [comment]
got a new error 
Class 'Saml2Auth' not found  :(

**Comment by aacotroneo** [comment]
hmm... this is strange.. This is just php... composer should load the autoload of all your dependencies (i.e this library).. and you should be able to use those classes. Try running a 'composer dump-autoload'.

**Comment by rendhon** [comment]
still having the error ! i also alreading updated my composer.json for the updates. but stiLL Class 'Saml2Auth' not found

**Comment by rendhon** [comment]
i already fixed it  sir. is just updated my composer.json for your new updates.. then applied my controller code on above.. thnx.. for kind reponse.. more power. :)

**Comment by aacotroneo** [comment]
Great. Im glad you got it working. Cheers
