### ISSUE TITLE
Reference validation failed error. 

### ISSUE THREAD

**Issue by ajithd-lbit** [aacotroneo/laravel-saml2#60]
When I am enabling the following security options, I am getting a 'Reference validation error'.

'authnRequestsSigned' => true,
'wantAssertionsSigned' => true,

**Comment by ajithd-lbit** [comment]
When I am enabling the following security options, I am getting a 'Reference validation error'. 

``'authnRequestsSigned' => true,``
``'wantAssertionsSigned' => true,``

**Comment by ajithd-lbit** [comment]
This issue is linked with https://github.com/onelogin/php-saml/issues/168

**Comment by msslgomez** [comment]
Anyone get this error `Reference validation error` recently?
