### ISSUE TITLE
Saml2LoginEvent doesn't fire in Laravel 5.3

### ISSUE THREAD

**Issue by robverhoef** [aacotroneo/laravel-saml2#61]
I have this in my EventServiceProvider:

```
public function boot() 
{
    parent::boot();

    Event::listen('Aacotroneo\Saml2\Events\Saml2LoginEvent', function (Saml2LoginEvent $event) {
        Log::info('Saml2LoginEvent');
    });
…
}
```

In my controller I have something like this:

```
public function acs(Request $request) {
    $samldata = $request->get('SAMLResponse');
…
}
```
My config settings look like this:

```
$idp_host = 'http://localhost/simplesaml';

return $settings = array(
    /*****
     * Cosmetic settings - controller routes
     **/
    'useRoutes' => true, //include library routes and controllers


    'routesPrefix' => '/saml2',

    /**
     * which middleware group to use for the saml routes
     * Laravel 5.2 will need a group which includes StartSession
     */
    'routesMiddleware' => ['web'],

… the rest is default

```

I have added the Saml routes to my web routes:
// Login lands here
Route::post('saml/acs', 'TestController@acs');
// Single Logout Services
Route::get('saml/sls', 'TestController@sls');

I do see the SAMLResponse coming in at TestController@acs and I can parse it with DOMXPath. 
So it looks like it's working. But I would expect the event being fired too…

Am I missing something or is this a bug?

**Comment by EmilMoe** [comment]
Did you fix this since it's closed?

**Comment by pkendre** [comment]
is it fixed? if yes, how you have solved this.
I am facing the same issue.

**Comment by pkendre** [comment]
finally i am able to make ii.

I replaced the line
`Event::listen('Aacotroneo\Saml2\Events\Saml2LoginEvent', function (Saml2LoginEvent $event) {`
by 
`Event::listen('Aacotroneo\Saml2\Events\Saml2LoginEvent', function (\Aacotroneo\Saml2\Events\Saml2LoginEvent $event) {`
and it worked.

Hope this help someone

**Comment by robverhoef** [comment]
Well done!
I had a gut feeling it wasn't a real bug and while I was working on it, my client dropped the idea of using SAML.
