### ISSUE TITLE
Invalid array settings: sp_acs_url_invalid

### ISSUE THREAD

**Issue by EmilMoe** [aacotroneo/laravel-saml2#67]
I updated my vendors today and now I have this error upon login. I think `onelogin/php-saml` has been updated and now your script is not compliant with it anymore.

~~~~
exception 'OneLogin_Saml2_Error' with message 'Invalid array settings: sp_acs_url_invalid'
~~~~

**Comment by EmilMoe** [comment]
The error can be resolved by changing the acs url to a absolute URL. This is not the best solution, I hope you come up with something.

**Comment by juanpscotto** [comment]
where I change that?
