### ISSUE TITLE
Disable SingleLogoutService for SP

### ISSUE THREAD

**Issue by JoeyHoutenbos** [aacotroneo/laravel-saml2#68]
Hi,

I don't want to expose a single-logout service, so I expected to do something like this in the "config/saml2_settings.php":

```
'sp' => array(
    ...
    'singleLogoutService' => false,
),
```

But this still sets up the service in the `Saml2ServiceProvider@register`. When I remove/comment out this part it is working:
```
if (empty($config['sp']['singleLogoutService']['url'])) {
    $config['sp']['singleLogoutService']['url'] = URL::route('saml_sls');
}
```

Why isn't this supported? Maybe it's better to check if the `singleLogoutService` even exists and if it does if the value isn't equal to `false` before inserting it.

@aacotroneo what do you think about it?

**Comment by aacotroneo** [comment]
yep, that could be a good improvement. It's not supported because no one needed/cared about it, but it does make sense. Something like this to remain the most backwards compatible we can?

```php
 if (!empty($config['sp']['singleLogoutService']) && 
     empty($config['sp']['singleLogoutService']['url']){
            $config['sp']['singleLogoutService']['url'] = URL::route('saml_sls');
 }
```

**Comment by JoeyHoutenbos** [comment]
I agree with you that would be the most backwards compatible solution.
This means in the settings the whole `singleLogoutService` part can be removed and it won't be added to the metadata.

Is this something you can include soon?

**Comment by aacotroneo** [comment]
I don't have an environment to test that at the time being. If you want to
make a PR with that change and check it's working, we can merge it and
include it in the next release.

2017-01-18 12:12 GMT-03:00 Joey <notifications@github.com>:

**Comment by JoeyHoutenbos** [comment]
I made a PR https://github.com/aacotroneo/laravel-saml2/pull/69. Please check it out and include in next release.
