### ISSUE TITLE
Preventing Replay Attacks

### ISSUE THREAD

**Issue by HughVolpe** [aacotroneo/laravel-saml2#90]
Reading the onelogin/php-saml Readme, they suggest tracking the message Ids to make sure you don't see a repeat. 

Is it possible to get at the message ids using this in order to track them in an application? 

If not at present, i think the best way would be to pass through the Saml2Auth object to the event and add a getter in to Saml2Auth to get the last message id from the OneLogin_Saml2_Auth object. I'm happy to make a pull request with this if you agree.

**Comment by aacotroneo** [comment]
yes, sounds good! And that wouldn't be a breaking change either!! so if you can do that it'd be appreciated

**Comment by HughVolpe** [comment]
Pull Request raised.

I was initially planning on passing through the message ids from logouts as well, but it doesn't seem like the variables are populated for the last message id by the onelogin/php-saml code on logouts. However reading in to it, I don't think its relevant to do that anyway. #91

**Comment by aacotroneo** [comment]
great, thanks. ill release a new version with this soon
