### ISSUE TITLE
Saml2 error ["invalid_response"]

### ISSUE THREAD

**Issue by nWidart** [aacotroneo/laravel-saml2#94]
Hello,

After getting a successful login on the IdP, the package is redirecting to the errorRoute with as error logged:
```
Saml2 error ["invalid_response"]
```

What could be the cause of this issue ? Would it be something on my end, or the provider's end ?

Thanks,

**Comment by RobertBoes** [comment]
Your IdP config probably doesn't have a valid x509cert config, I had the same error.

You can set the value of x509cert to the contents of the public certificate from you IdP.

**Comment by nWidart** [comment]
Thanks for the heads up.

By looking at the php-saml request I could get a more precise error, which is described here: https://github.com/onelogin/php-saml/issues/232
